### ISSUE TITLE
Importing History doesn't work anymore

### ISSUE THREAD

**Issue by KitsuneFM** [MadeBaruna/pom-moe#11]
Both methods stopped working.

CMD version gives `Cannot find the wish history url! Make sure to open the wish history first!` error message.
**data_2** file version says `no_url_found`.

Everything worked fine recently. I think they could have changed something in 1.2.

EDIT: I also want to add that I know I have to go to history in-game for the cmd method to work. But the problem is, it doesn't work despite I am there. Tried to enter multiple times and still not working. Even had reset the game, because I stopped playing and continued later on.

**Comment by Cherrywoood** [comment]
Yes, I have this issue too

**Comment by RavenQweenz** [comment]
I am having a similar issue where data_2 says the connection failed and then when I use the second method it goes down 66 lines and says it couldn't find anything.

**Comment by cptmacp** [comment]
Use this 


`[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12; Invoke-Expression (New-Object Net.WebClient).DownloadString("https://gist.githubusercontent.com/Star-Rail-Station/2512df54c4f35d399cc9abbde665e8f0/raw/get_warp_link_os.ps1?cachebust=srs")`


Source 

https://starrailstation.com/en/warp#import

**Comment by KitsuneFM** [comment]
> Use this
Thanks! I didn't know there is another Warp counter. Now I don't need to manually count pulls 😂

**Comment by MadeBaruna** [comment]
Fixed on https://github.com/MadeBaruna/pom-moe/commit/6da3457d75293b13959ca802c4802a2a762cad15
